server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xinke?characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: ycwycw123

mvc:
  static-path-pattern: /static/**  #配置静态路径

mybatis:
  type-aliases-package: com.xkyz.xinke.model
  mapper-locations: classpath:com/xkyz/xinke/mapper/**/*.xml
